### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by roboticsalign** [sven819/SharpClimateUART-ESPHome#7]
Dear all,

the compilation fails and I am not sure, if the fault is on my configuration or in the code. 

**Logs**:
```
INFO ESPHome 2025.2.0
INFO Reading configuration /config/esphome/esphome-buderus-buero.yaml...
INFO Updating https://github.com/sven819/SharpClimateUART-ESPHome.git@None
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-buderus-buero (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)

HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/esphome-buderus-buero/src/esphome/components/sharp_ac/sharp_ac.cpp.o
Compiling .pioenvs/esphome-buderus-buero/src/esphome/components/switch/switch.cpp.o
Compiling .pioenvs/esphome-buderus-buero/src/esphome/components/uart/uart.cpp.o
Compiling .pioenvs/esphome-buderus-buero/src/esphome/components/uart/uart_component.cpp.o
Compiling .pioenvs/esphome-buderus-buero/src/esphome/components/uart/uart_component_esp32_arduino.cpp.o
In file included from src/esphome/components/climate/climate.h:7,
                 from src/esphome/components/sharp_ac/sharp_ac.h:3,
                 from src/esphome/components/sharp_ac/sharp_ac.cpp:1:
src/esphome/components/sharp_ac/sharp_ac.cpp: In member function 'void esphome::sharp_ac::SharpAc::init(SharpFrame&)':
src/esphome/core/log.h:97:3: error: expected unqualified-id before '::' token
   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_DEBUG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
   ^~
src/esphome/core/log.h:154:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^~~~~~~~~~
src/esphome/components/sharp_ac/sharp_ac.cpp:80:16: note: in expansion of macro 'ESP_LOGD'
       esphome::ESP_LOGD("ac_frame", "Sharp INIT Data: %s", esphome::format_hex_pretty(frame.getData(), frame.getSize()).c_str());
                ^~~~~~~~
src/esphome/components/sharp_ac/sharp_ac.cpp: In member function 'virtual void esphome::sharp_ac::SharpAc::loop()':
src/esphome/core/log.h:97:3: error: expected unqualified-id before '::' token
   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_DEBUG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
   ^~
src/esphome/core/log.h:154:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^~~~~~~~~~
src/esphome/components/sharp_ac/sharp_ac.cpp:292:20: note: in expansion of macro 'ESP_LOGD'
           esphome::ESP_LOGD("ac_frame", "Sharp Frame Data: %s", esphome::format_hex_pretty(frame.getData(), frame.getSize()).c_str());
                    ^~~~~~~~
src/esphome/components/sharp_ac/sharp_ac.cpp: In member function 'virtual void esphome::sharp_ac::SharpAc::control(const esphome::climate::ClimateCall&)':
src/esphome/core/log.h:97:3: error: expected unqualified-id before '::' token
   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_DEBUG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
   ^~
src/esphome/core/log.h:154:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^~~~~~~~~~
src/esphome/components/sharp_ac/sharp_ac.cpp:412:16: note: in expansion of macro 'ESP_LOGD'
       esphome::ESP_LOGD("ac_frame", "Sharp Frame Data: %s", esphome::format_hex_pretty(frame.getData(), frame.getSize()).c_str());
                ^~~~~~~~
Compiling .pioenvs/esphome-buderus-buero/src/esphome/components/uart/uart_component_esp8266.cpp.o
Compiling .pioenvs/esphome-buderus-buero/src/esphome/components/uart/uart_component_esp_idf.cpp.o
*** [.pioenvs/esphome-buderus-buero/src/esphome/components/sharp_ac/sharp_ac.cpp.o] Error 1
========================== [FAILED] Took 4.93 seconds ==========================
```

**Configuration**:
```
substitutions:
  nr: "2"
  devicename: esphome-buderus-buero
  deviceid: hvac${nr}


esphome:
  name: ${devicename}
  friendly_name: ${devicename}

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: arduino
  
external_components:
  - source: github://sven819/SharpClimateUART-ESPHome
    refresh: 0s

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
#    safe_mode: true
    password: !secret ota_password

# Enable logging
logger:
  baud_rate: 0 # disable serial logging if you're using the standard TX/RX pins for your serial peripheral
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
    
web_server:
  port: 80
  version: 3

uart:
  tx_pin: 1         # hardware dependent
  rx_pin: 3         # hardware dependent
  baud_rate: 9600
  parity: EVEN

button:
  - platform: restart
    name: "EG Buero Restart"

climate:
  - platform: sharp_ac     
    id: hvac
    name: "EG Buero Klimaanlage"
    horizontal_vane_select: 
      name: "Horizontal Vane"
    vertical_vane_select: 
      name: "Vertikal Vane"
    ion_switch:
      name: "Plasmacluster"
```

Do you have any suggestions for further debugging?
